### ISSUE TITLE
Confusing error messages when input shape doesn't match subscripts

### ISSUE THREAD

**Issue by bbbbbbbbba** [dgasmith/opt_einsum#130]
```
>>> import numpy as np
>>> import opt_einsum as oe
>>> oe.contract('A,A->A', np.zeros((2,)), np.zeros((2, 2)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/loaner/Library/Python/3.7/lib/python/site-packages/opt_einsum/contract.py", line 477, in contract
    use_blas=use_blas)
  File "/Users/loaner/Library/Python/3.7/lib/python/site-packages/opt_einsum/contract.py", line 223, in contract_path
    "correct number of indices for operand {}.".format(input_subscripts[tnum], tnum))
ValueError: Einstein sum subscript ',' does not contain the correct number of indices for operand 1.
```

Apparently this is caused by a simple misuse of variable, where on line 233 `input_list` should be used instead of `input_subscripts`.

https://github.com/dgasmith/opt_einsum/blob/84a805d35ee501abfce7a07030103a209f568af2/opt_einsum/contract.py#L213-L233

**Comment by jcmgray** [comment]
Yep that looks like a simple bug. I can fix.

**Comment by dgasmith** [comment]
Thanks @jcmgray!

```python
>>> oe.contract('A,B->A', np.zeros((2,)), np.zeros((2, 2)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/Gits/opt_einsum/opt_einsum/contract.py", line 477, in contract
    use_blas=use_blas)
  File "/Users/daniel/Gits/opt_einsum/opt_einsum/contract.py", line 223, in contract_path
    "correct number of indices for operand {}.".format(input_list[tnum], tnum))
ValueError: Einstein sum subscript 'B' does not contain the correct number of indices for operand 1.
```
