### ISSUE TITLE
Problem with sparse

### ISSUE THREAD

**Issue by Tomohirohashizume** [dgasmith/opt_einsum#139]
`Sparse version 0.9.1`
`opt_einsum.__version__ = '0+untagged.56.g2664021.dirty'`
Following code returns error `AttributeError: sparse doesn't seem to provide the function einsum
` (detailed output follows the code)
```
import opt_einsum as oe
import sparse as sp

shapes = (3, 200), (200, 300), (300, 4)

sxs = [sp.random(shp) for shp in shapes]
print (sxs)
sy = oe.contract("ab,bc,cd->bd", *sxs)
print(sy)
```
Error message:
```
Traceback (most recent call last):
  File "einsumtest.py", line 8, in <module>
    sy = oe.contract("ab,bc,cd->bd", *sxs)
  File "/path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/contract.py", line 483, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/contract.py", line 567, in _core_contract
    new_view = _einsum(einsum_str, *tmp_operands, backend=backend, **einsum_kwargs)
  File "/path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/sharing.py", line 151, in cached_einsum
    return einsum(*args, **kwargs)
  File "/path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/contract.py", line 324, in _einsum
    fn = backends.get_func('einsum', kwargs.pop('backend', 'numpy'))
  File "path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/backends/dispatch.py", line 59, in get_func
    fn = _import_func(func, backend, default)
  File "/path/.conda/envs/baseenv/lib/python3.7/site-packages/opt_einsum/backends/dispatch.py", line 40, in _import_func
    raise AttributeError("{} doesn't seem to provide the function {}".format(backend, func))
AttributeError: sparse doesn't seem to provide the function einsum

**Comment by dgasmith** [comment]
The operation you are showing requires operations beyond BLAS (GEMM) functionality and therefore isn't executable with Sparse automatically. We rely on an einsum-like operation to sum over arbitrary indices for non-BLAS operations. For example `oe.contract("ab,bc,cd->ad", *sxs)` should work fine as it is chained GEMM operations.

It also looks like your `opt_einsum` is quite old.

**Comment by jcmgray** [comment]
Might be worth extending this error message since there have been a few issues like this. Maybe with a link to the [backends docs](https://optimized-einsum.readthedocs.io/en/stable/backends.html) which have a note about when ``einsum`` is still required.

**Comment by Tomohirohashizume** [comment]
Okay, that makes sense. Thank you very much.
Any of you can close, or you can close this after the documentation is extended.
