### ISSUE TITLE
dask backend attempts to use non-existent dask einsum function on an einsum broadcasting example

### ISSUE THREAD

**Issue by sjperkins** [dgasmith/opt_einsum#22]
From my reading of the code, broadcasting disables blas, which then defers to the dask einsum backend, which does not exist. This happens on master https://github.com/dgasmith/opt_einsum/commit/c235f0c1f4a0d2bfbd51137a5aee99eb72767f70

```python
import dask.array as da
from opt_einsum import contract

# Produce random dask floats
rf = lambda s,c: da.random.random(size=s, chunks=c)

I = rf((10, 10, 10, 10), (5,5,5,5))
C = rf((10, 10), (5,5))

# Example in the docs, this works
result = contract('ea,fb,abcd,gc,hd->efgh', C, C, I, C, C,
                               optimize='greedy', backend='dask')

# dim sizes and their chunks
s = 10
sc = (5,5)
t = 5
tc = (2,3)
a = 7
ac = (3,4)
c = 4
cc = (2,2)

# This fails
result = contract('sta,tac->stac',
    rf((s,t,a), (sc,tc,ac)),
    rf((t,a,c), (tc,ac,cc)),
    backend='dask')
```

produces

```bash
$ python test_opt_einsum.py 
Traceback (most recent call last):
  File "test_opt_einsum.py", line 26, in <module>
    backend='dask')
  File "/home/sperkins/venv/opt_einsum/local/lib/python2.7/site-packages/opt_einsum/contract.py", line 423, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/sperkins/venv/opt_einsum/local/lib/python2.7/site-packages/opt_einsum/contract.py", line 484, in _core_contract
    new_view = _einsum(einsum_str, *tmp_operands, backend=backend, **einsum_kwargs)
  File "/home/sperkins/venv/opt_einsum/local/lib/python2.7/site-packages/opt_einsum/contract.py", line 280, in _einsum
    fn = backends.get_func('einsum', kwargs.pop('backend', 'numpy'))
  File "/home/sperkins/venv/opt_einsum/local/lib/python2.7/site-packages/opt_einsum/backends.py", line 39, in get_func
    fn = _import_func(func, backend)
  File "/home/sperkins/venv/opt_einsum/local/lib/python2.7/site-packages/opt_einsum/backends.py", line 21, in _import_func
    raise AttributeError("{} doesn't seem to provide the function {}".format(backend, func))
AttributeError: dask doesn't seem to provide the function einsum
```

**Comment by dgasmith** [comment]
Hmm, thats not good. Im not super familiar with that part of Dask, but I would have thought it would call `np.einsum` there. @jcmgray should have more as he worked on this functionality.

**Comment by dgasmith** [comment]
As a note, a PR has been opened [here](https://github.com/dask/dask/pull/3412) to allow `dask.einsum`.

**Comment by dgasmith** [comment]
Closed by https://github.com/dask/dask/pull/3412.
