### ISSUE TITLE
pip install opt_einsum fails due to versioneer

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#40]
When I try to `pip install opt_einsum` I get an error
```
$ pip install opt_einsum -U
Collecting opt_einsum
  Using cached https://files.pythonhosted.org/packages/30/52/64ed28228334a1124c082809402c01c4219085c5ee0f34991ace24a10dad/opt_einsum-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-AyuWKs/opt-einsum/setup.py", line 4, in <module>
        import versioneer
    ImportError: No module named versioneer

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-AyuWKs/opt-einsum/
```
When I then try to fix the missing dependency via `pip install versioneer`, I get
```
$ pip install versioneer
# ...
$ pip install opt_einsum
Collecting opt_einsum
  Using cached https://files.pythonhosted.org/packages/30/52/64ed28228334a1124c082809402c01c4219085c5ee0f34991ace24a10dad/opt_einsum-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-SZkOZK/opt-einsum/setup.py", line 12, in <module>
        version=versioneer.get_version(),
    AttributeError: 'module' object has no attribute 'get_version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-SZkOZK/opt-einsum/
```

## System info

```
$ python --version
Python 2.7.14 :: Anaconda, Inc.
$ uname -a
Darwin fritzo-C02V61MRHTDG 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by fritzo** [comment]
Have you tried `pip install`? I've had similar bugs arise when I only ever `pip install --editable` and never try to install from pypi, since the local install has access to the `versioneer.py` script but this script is not included in the pip bundle.

**Comment by eb8680** [comment]
I'm seeing the same issue on Ubuntu 18.04

**Comment by dgasmith** [comment]
Yup, needs a `MANIFEST.in`, making a PR now. Thanks for the alert.

**Comment by dgasmith** [comment]
@faroit @eb8680 Thanks for the quick report, please try `pip install opt_einsum` again.

**Comment by faroit** [comment]
works here 👍 (OSX, 3.6)

**Comment by dgasmith** [comment]
@faroit Thanks for checking! Let us see how it applies to other systems before closing.

**Comment by fritzo** [comment]
Thanks for fixing so quickly! Works for me: OS X + Python 2.7

**Comment by dgasmith** [comment]
Thanks for the feedback! Glad the patch fixed up your issue.
